#!/bin/bash

# Restart vim with the most recent N files from ~/.vim_mru_files.  


MruFileCount=8

PaneCount=1


addArgs=""

function parseArgs {
	while [[ ! -z $1 ]]; do
		case $1 in
			-n)
				MruFileCount=$2
				shift
				;;

			-p | -O) # Set number of panes:
				PaneCount=$2
				shift
				;;
			*)
				addArgs="$addArgs $1"
				;;
		esac
		shift
	done
}

function quoteMruFilenames {
    exec 8< <(grep -v '^#' ${HOME}/.vim_mru_files | head -n $MruFileCount)

    while read -u 8 line; do
        echo -n "\"$line\" "
    done
    
    exec 8<&-
}


if [[ -z $sourceMe ]]; then
    parseArgs "$@"

    # Scrape the file list:
    files="$(grep -v '^#' ${HOME}/.vim_mru_files | head -n $MruFileCount)"

    
    cmdline="vim -O${PaneCount} $addArgs $(quoteMruFilenames)"
    echo "Command line: $cmdline"
    echo "$cmdline" > /dev/clipboard
    eval $cmdline
fi

