" after/ftplugin/ts.vim
" Auto-generated by fix_ftplugin_formatoptions in taskrc 
"
" We like our comment-related formatoptions in general, and do not like the
" master ftplugin.vim to reset them (see also:
"    - https://vi.stackexchange.com/a/19010/7649 
"    - help formatoptions)
"
"
setlocal formatoptions+=o
setlocal formatoptions+=r

